export {default as Main} from './Main';
export {default as Ailments} from './Ailments';
export {default as Navbar} from './Navbar';
export {default as Weapons} from './Weapons';
export {default as Home} from './Home';
export {default as Armor} from './Armor';
export {default as GreatSword} from './GreatSword';
export {default as Bow} from './Bow';
export {default as ChargeBlade} from './ChargeBlade'
export {default as DualBlades} from './DualBlades';
export {default as Gunlance} from './Gunlance';
export {default as Hammer} from './Hammer'
export {default as Hbg} from './Hbg'
export {default as HuntingHorn} from './HuntingHorn'
export {default as InsectGlaive} from './InsectGlaive'
export {default as Lance} from './Lance'
export {default as Lbg} from './Lbg'
export {default as LongSword} from './LongSword'
export {default as SnS} from './SnS'
export {default as SwitchAxe} from './SwitchAxe'